"use client";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue
} from "@/components/ui/select";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow
} from "@/components/ui/table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  useGenerateAiInsightsMutation,
  useGetAiInsightsQuery
} from "@/store/services/ai-insight.service";
import { getCookie } from "@/utils/cookies";
import {
  AlertTriangle,
  ArrowRight,
  Bell,
  BrainCircuit,
  CheckCircle,
  Info,
  Loader2,
  Package,
  TrendingUp
} from "lucide-react";
import { useState } from "react";
import {
  CartesianGrid,
  Line,
  LineChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis
} from "recharts";
import { toast } from "sonner";

export default function AiInsightsDashboardPage() {
  const branchId = getCookie("pos_branch_id");
  const {
    data: aiData,
    isLoading,
    isFetching
  } = useGetAiInsightsQuery(branchId ? { branchId } : {});
  const [generateAiInsights, { isLoading: isGenerating }] = useGenerateAiInsightsMutation();
  const [timeRange, setTimeRange] = useState("monthly");

  const insights = Array.isArray(aiData) ? aiData : [];

  const salesTrends = insights.filter((i: any) => i.type === "sales_trend");
  const recommendations = insights.filter((i: any) =>
    ["stock_suggestion", "best_seller", "slow_moving"].includes(i.type)
  );
  const alerts = insights.filter((i: any) =>
    ["low_stock_alert", "expiry_alert", "anomaly_alert"].includes(i.type)
  );
  const summary = insights.find((i: any) => i.type === "report_summary") || {};
  const summaryMetadata = summary.metadata || {};

  const handleGenerateAnalysis = async () => {
    try {
      await generateAiInsights({
        branchId: branchId || "",
        timeRange
      }).unwrap();
      toast.success(`AI Analysis (${timeRange}) generated successfully!`);
    } catch (error: any) {
      toast.error(error?.data?.message || "Failed to generate analysis.");
    }
  };

  return (
    <div className="space-y-6 p-6">
      {/* Header Section */}
      <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
        <div className="space-y-1">
          <h1 className="text-3xl font-bold tracking-tight">AI Insights Dashboard</h1>
          <p className="text-muted-foreground">
            comprehensive AI-powered analysis of your business performance.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Select value={timeRange} onValueChange={setTimeRange}>
            <SelectTrigger className="bg-background w-[180px]">
              <SelectValue placeholder="Select range" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="weekly">Weekly (7 Days)</SelectItem>
              <SelectItem value="monthly">Monthly (30 Days)</SelectItem>
              <SelectItem value="yearly">Yearly (365 Days)</SelectItem>
            </SelectContent>
          </Select>

          <Button
            onClick={handleGenerateAnalysis}
            disabled={isLoading || isFetching || isGenerating}
            size="lg"
            className="bg-linear-to-r from-indigo-500 to-purple-600 text-white shadow-lg transition-all duration-300 hover:from-indigo-600 hover:to-purple-700">
            {isLoading || isFetching || isGenerating ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Generating...
              </>
            ) : (
              <>
                <BrainCircuit className="mr-2 h-4 w-4" />
                Generate
              </>
            )}
          </Button>
        </div>
      </div>

      {isLoading ? (
        <div className="flex h-[60vh] flex-col items-center justify-center gap-4">
          <Loader2 className="text-primary h-10 w-10 animate-spin" />
          <p className="text-muted-foreground animate-pulse">Gathering intelligence...</p>
        </div>
      ) : (
        <div className="grid gap-6">
          {/* Top Section: AI Summary & Highlights */}
          <div className="grid gap-6 md:grid-cols-3">
            <Card className="border-l-primary border-l-4 md:col-span-2">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <BrainCircuit className="text-primary h-5 w-5" />
                  Executive Summary
                </CardTitle>
                <CardDescription>
                  High-level overview generated by AI based on recent data.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="prose dark:prose-invert max-w-none">
                  <p className="text-muted-foreground text-lg leading-relaxed">
                    {summaryMetadata.executive_summary ||
                      "No summary available. Click 'Generate AI Analysis' to start."}
                  </p>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <TrendingUp className="h-5 w-5 text-green-500" />
                  Key Highlights
                </CardTitle>
              </CardHeader>
              <CardContent>
                <ul className="space-y-4">
                  {(summaryMetadata.highlights || [])
                    .slice(0, 5)
                    .map((highlight: string, index: number) => (
                      <li key={index} className="flex items-start gap-3">
                        <div className="mt-1 rounded-full bg-green-100 p-1 dark:bg-green-900/30">
                          <CheckCircle className="h-3 w-3 text-green-600 dark:text-green-400" />
                        </div>
                        <span className="text-sm font-medium">{highlight}</span>
                      </li>
                    ))}
                  {(!summaryMetadata.highlights || summaryMetadata.highlights.length === 0) && (
                    <li className="text-muted-foreground text-sm">No highlights found.</li>
                  )}
                </ul>
              </CardContent>
            </Card>
          </div>

          {/* Middle Section: Sales Trends Chart */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <TrendingUp className="h-5 w-5 text-blue-500" />
                Sales Trends Analysis
              </CardTitle>
              <CardDescription>Revenue performance over time.</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="h-[350px] w-full">
                <ResponsiveContainer width="100%" height="100%">
                  <LineChart data={salesTrends}>
                    <CartesianGrid
                      strokeDasharray="3 3"
                      className="stroke-muted/30"
                      vertical={false}
                    />
                    <XAxis
                      dataKey="date"
                      className="text-muted-foreground text-xs"
                      tickLine={false}
                      axisLine={false}
                      tickMargin={10}
                    />
                    <YAxis
                      className="text-muted-foreground text-xs"
                      tickLine={false}
                      axisLine={false}
                      tickFormatter={(value) => `$${value}`}
                    />
                    <Tooltip
                      content={({ active, payload }) => {
                        if (active && payload && payload.length) {
                          return (
                            <div className="bg-background rounded-lg border p-3 shadow-xl ring-1 ring-black/5">
                              <div className="flex flex-col gap-1">
                                <span className="text-muted-foreground text-[0.70rem] font-semibold uppercase">
                                  {payload[0].payload.date}
                                </span>
                                <span className="text-primary text-lg font-bold">
                                  ${Number(payload[0].value).toFixed(2)}
                                </span>
                              </div>
                            </div>
                          );
                        }
                        return null;
                      }}
                    />
                    <Line
                      type="monotone"
                      dataKey="amount"
                      stroke="hsl(var(--primary))"
                      strokeWidth={3}
                      dot={{ r: 4, strokeWidth: 2 }}
                      activeDot={{ r: 6, strokeWidth: 0 }}
                    />
                  </LineChart>
                </ResponsiveContainer>
              </div>
            </CardContent>
          </Card>

          {/* Bottom Section: Tabs for Stock & Alerts */}
          <Tabs defaultValue="stock" className="w-full">
            <TabsList className="grid w-full grid-cols-2 lg:w-[400px]">
              <TabsTrigger value="stock">Stock Recommendations</TabsTrigger>
              <TabsTrigger value="alerts">System Alerts</TabsTrigger>
            </TabsList>

            <TabsContent value="stock" className="mt-4">
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Package className="h-5 w-5 text-purple-500" />
                    Restock Recommendations
                  </CardTitle>
                  <CardDescription>AI-suggested inventory replenishment actions.</CardDescription>
                </CardHeader>
                <CardContent>
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>Product</TableHead>
                        <TableHead>Current Stock</TableHead>
                        <TableHead>Recommended</TableHead>
                        <TableHead>Priority</TableHead>
                        <TableHead className="text-right">Action</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {recommendations.length === 0 ? (
                        <TableRow>
                          <TableCell colSpan={5} className="text-muted-foreground py-8 text-center">
                            No stock recommendations at this time.
                          </TableCell>
                        </TableRow>
                      ) : (
                        recommendations.map((item: any, index: number) => {
                          const meta = item.metadata || {};
                          return (
                            <TableRow key={index}>
                              <TableCell className="font-medium">
                                <div className="flex items-center gap-2">
                                  <Package className="text-muted-foreground h-4 w-4" />
                                  {meta.product_name || item.summary || "Unknown Product"}
                                </div>
                              </TableCell>
                              <TableCell>{meta.current_stock || "N/A"}</TableCell>
                              <TableCell className="font-bold text-green-600">
                                +{meta.recommended_quantity || 0}
                              </TableCell>
                              <TableCell>
                                <Badge
                                  variant={meta.priority === "high" ? "destructive" : "secondary"}
                                  className="capitalize">
                                  {meta.priority || "medium"}
                                </Badge>
                              </TableCell>
                              <TableCell className="text-right">
                                <Button size="sm" variant="outline" className="h-8">
                                  Create PO <ArrowRight className="ml-2 h-3 w-3" />
                                </Button>
                              </TableCell>
                            </TableRow>
                          );
                        })
                      )}
                    </TableBody>
                  </Table>
                </CardContent>
              </Card>
            </TabsContent>

            <TabsContent value="alerts" className="mt-4">
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Bell className="h-5 w-5 text-orange-500" />
                    Active Alerts
                  </CardTitle>
                  <CardDescription>Operational warnings and system notifications.</CardDescription>
                </CardHeader>
                <CardContent>
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>Severity</TableHead>
                        <TableHead>Type</TableHead>
                        <TableHead>Message</TableHead>
                        <TableHead>Date</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {alerts.length === 0 ? (
                        <TableRow>
                          <TableCell colSpan={4} className="text-muted-foreground py-8 text-center">
                            No active alerts at this time.
                          </TableCell>
                        </TableRow>
                      ) : (
                        alerts.map((alert: any, index: number) => {
                          const meta = alert.metadata || {};
                          return (
                            <TableRow key={index}>
                              <TableCell>
                                <Badge
                                  variant={
                                    meta.severity === "critical" || meta.severity === "high"
                                      ? "destructive"
                                      : "outline"
                                  }
                                  className={`capitalize ${
                                    meta.severity === "warning" || meta.severity === "medium"
                                      ? "border-orange-200 bg-orange-100 text-orange-800 dark:border-orange-800 dark:bg-orange-900/30 dark:text-orange-300"
                                      : ""
                                  }`}>
                                  {meta.severity || "info"}
                                </Badge>
                              </TableCell>
                              <TableCell>
                                <div className="flex items-center gap-2">
                                  {meta.type === "critical" ? (
                                    <AlertTriangle className="text-destructive h-4 w-4" />
                                  ) : meta.type === "warning" ? (
                                    <Bell className="h-4 w-4 text-orange-500" />
                                  ) : (
                                    <Info className="h-4 w-4 text-blue-500" />
                                  )}
                                  <span className="text-sm font-medium capitalize">
                                    {meta.type || alert.type.replace(/_/g, " ")}
                                  </span>
                                </div>
                              </TableCell>
                              <TableCell className="font-medium">
                                {meta.message || alert.summary}
                              </TableCell>
                              <TableCell className="text-muted-foreground text-sm">
                                {new Date(
                                  alert.createdAt || alert.created_at || new Date()
                                ).toLocaleDateString()}
                              </TableCell>
                            </TableRow>
                          );
                        })
                      )}
                    </TableBody>
                  </Table>
                </CardContent>
              </Card>
            </TabsContent>
          </Tabs>
        </div>
      )}
    </div>
  );
}
