"use client";

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { useGetAiInsightsQuery } from "@/store/services/ai-insight.service";
import { AlertTriangle, BrainCircuit, CheckCircle, TrendingUp } from "lucide-react";

export default function AiSummaryReportPage() {
  const { data: aiData, isLoading } = useGetAiInsightsQuery({});
  const summary = aiData?.data?.summary || {};

  return (
    <div className="space-y-6 p-6">
      <div className="flex flex-col gap-2">
        <h1 className="text-3xl font-bold tracking-tight">AI Summary Report</h1>
        <p className="text-muted-foreground">
          Comprehensive analysis and executive summary generated by AI.
        </p>
      </div>

      {isLoading ? (
        <div className="flex h-64 items-center justify-center">
          <div className="text-muted-foreground">Generating summary...</div>
        </div>
      ) : (
        <div className="grid gap-6 md:grid-cols-2">
          <Card className="col-span-2">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <BrainCircuit className="text-primary h-5 w-5" />
                Executive Summary
              </CardTitle>
              <CardDescription>High-level overview of business performance.</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="prose dark:prose-invert max-w-none">
                <p className="text-muted-foreground leading-relaxed">
                  {summary.executive_summary ||
                    "No summary available at this moment. Please check back later when enough data is gathered."}
                </p>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <TrendingUp className="h-5 w-5 text-green-500" />
                Key Highlights
              </CardTitle>
            </CardHeader>
            <CardContent>
              <ul className="space-y-3">
                {(summary.highlights || []).map((highlight: string, index: number) => (
                  <li key={index} className="flex items-start gap-2">
                    <CheckCircle className="mt-0.5 h-4 w-4 shrink-0 text-green-500" />
                    <span className="text-sm">{highlight}</span>
                  </li>
                ))}
                {(!summary.highlights || summary.highlights.length === 0) && (
                  <li className="text-muted-foreground text-sm">No specific highlights found.</li>
                )}
              </ul>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <AlertTriangle className="h-5 w-5 text-orange-500" />
                Risks & Opportunities
              </CardTitle>
            </CardHeader>
            <CardContent>
              <ul className="space-y-3">
                {(summary.risks_opportunities || []).map((item: string, index: number) => (
                  <li key={index} className="flex items-start gap-2">
                    <div className="mt-1.5 h-2 w-2 shrink-0 rounded-full bg-orange-500" />
                    <span className="text-sm">{item}</span>
                  </li>
                ))}
                {(!summary.risks_opportunities || summary.risks_opportunities.length === 0) && (
                  <li className="text-muted-foreground text-sm">
                    No significant risks or opportunities detected.
                  </li>
                )}
              </ul>
            </CardContent>
          </Card>
        </div>
      )}
    </div>
  );
}
